/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type FerrumDB = FerrumDb
/** The main FerrumDB class for Node.js. */
export declare class FerrumDb {
  /** Open a FerrumDB database at the given path. Options: { encryptionKey: string } */
  static open(path: string, options?: { encryptionKey?: string }): FerrumDb
  /** Get a value by key. Returns the value or null if not found. */
  get(key: string): unknown
  /** Set a key to a JSON-serializable value. */
  set(key: string, value: unknown): void
  /** Set a key with a TTL (time-to-live) in seconds. Auto-expires after the duration. */
  setEx(key: string, value: unknown, ttlSeconds: number): void
  /** Delete a key. Returns true if it existed, false if not found. */
  delete(key: string): boolean
  /** List all existing keys in the database. */
  keys(): Array<string>
  /** Return the total number of entries. */
  count(): number
  /** Launch Ferrum Studio web dashboard. Runs in the background. */
  startStudio(port?: number): void
  /** Create a secondary index on a specific JSON field. */
  createIndex(field: string): void
  /** Find all keys where the given field matches the given value. */
  find(field: string, value: string): Array<string>
  /** Commit a transaction atomically. */
  commit(tx: Transaction): void
}
/** A transaction builder. Use with `db.commit(tx)`. */
export declare class Transaction {
  /** Create a new empty transaction. */
  constructor()
  /** Stage a SET operation. */
  set(key: string, value: unknown): void
  /** Stage a SET operation with TTL in seconds. */
  setEx(key: string, value: unknown, ttlSeconds: number): void
  /** Stage a DELETE operation. */
  delete(key: string): void
}
